#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/src
export VIRTUALENVWRAPPER_SCRIPT=/usr/bin/virtualenvwrapper.sh
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3

# For Eniram make-dev-env.sh
export ENVDIR=$WORKON_HOME
export PYTHON=$HOME/.pyenv/shims/python
export AXIS=enipy2016


export GIT_EDITOR=vim



export LDFLAGS="-arch x86_64 -Wall  -L/usr/local/lib -undefined dynamic_lookup  -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib  -ldl -framework CoreFoundation "
export CFLAGS="-arch x86_64 -I /usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include"
 
