#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# profile zsh startup https://stevenvanbael.com/profiling-zsh-startup
#zmodload zsh/zprof

# Fast git autocompletion. Must be before plugins
# https://superuser.com/questions/458906/zsh-tab-completion-of-git-commands-is-very-slow-how-can-i-turn-it-off
__git_files () { 
    _wanted files expl 'local files' _files     
}

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source /usr/bin/virtualenvwrapper-3.sh

# Allow > to truncate file, see https://unix.stackexchange.com/questions/212127/zsh-disable-file-exists-warning-with-redirection
setopt clobber

# maven autocomplete
ifpath=($ZPREZTODIR/ext_modules/zsh-completions/src/ $fpath)



# Gcloud auto-complete https://github.com/littleq0903/gcloud-zsh-completion
if [[ -d ~/.local/opt/gcloud-zsh-completion/src ]]; then
	fpath=(~/.local/opt/gcloud-zsh-completion/src $fpath)
	autoload -U compinit compdef
	compinit
fi

# support bash autocompletion
# https://stackoverflow.com/questions/3249432/i-have-a-bash-tab-completion-script-is-there-a-simple-way-to-use-it-from-zsh
autoload bashcompinit
bashcompinit

if [[ -f /usr/share/bash-completion/completions/lpass ]]; then
	source /usr/share/bash-completion/completions/lpass
fi

if which rustup > /dev/null ; then
	rustup completions zsh > ~/.cache/rustup_completions_zsh_cached
	fpath=(~/.cache/rustup_completions_zsh_cached $fpath)
	compinit
fi

# snap / snappy autocomplete
if [[ -f $ZPREZTODIR/ext_modules/Snappy/_snap ]]; then
	source $ZPREZTODIR/ext_modules/Snappy/_snap
fi

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /home/salski/src/finance-scraper/node_modules/tabtab/.completions/serverless.zsh ]] && . /home/salski/src/finance-scraper/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /home/salski/src/finance-scraper/node_modules/tabtab/.completions/sls.zsh ]] && . /home/salski/src/finance-scraper/node_modules/tabtab/.completions/sls.zsh


#{ flatpak list|grep -q com.visualstudio.code.oss } && { alias vscode='flatpak run com.visualstudio.code.oss' ; alias code=vscode }

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/salski/.sdkman"
[[ -s "/home/salski/.sdkman/bin/sdkman-init.sh" ]] && source "/home/salski/.sdkman/bin/sdkman-init.sh"

# profiling slow startup
#zprof
